once more try and get this to work

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,20 +7,22 @@ env:
     container: "registry.access.redhat.com/rhel7"
     init: /usr/lib/systemd/systemd
     run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
-    ansible_opts: "--extra-vars \"@/etc/ansible/roles/role_under_test/tests/extra_vars.yml\" --skip-tags=\"auditd\""
   - distro: centos
     version: 7
     container: "centos:7"
     init: /usr/lib/systemd/systemd
     run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
-    ansible_opts: "--extra-vars \"@/etc/ansible/roles/role_under_test/tests/extra_vars.yml\" --skip-tags=\"auditd\""
 
 services: docker
 
 before_install:
   # Pull container.
   - 'docker pull ${container}'
-  - docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests
+  - 'if [ ${distro} = "rhel" ]; then
+        docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
+     else
+        docker build --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
+     fi'
 
 script:
   - container_id=$(mktemp)
@@ -32,14 +34,12 @@ script:
   - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --syntax-check'
 
   # Test role.
-  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml ${ansible_opts}
+  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars.yml" --skip-tags="auditd"
 
   # Test role idempotence.
   - idempotence=$(mktemp)
 
-  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml ${ansible_opts} | tee -a ${idempotence}
-  - >
-  - 'tail ${idempotence} | grep -q "changed=0.*failed=0" && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'
+  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars.yml" --skip-tags="auditd" | tee -a ${idempotence} > tail ${idempotence} | grep -q "changed=0.*failed=0" && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'
 
   # Deregister
   - 'if [ ${distro} = "rhel" ]; then
